### ISSUE TITLE
结合GmSSL-3.1.1编译报错,未知的类型名‘SM3_DIGEST_CTX’

### ISSUE THREAD

**Issue by 1156175523** [GmSSL/OpenSSL-Compatibility-Layer#3]
我这边测试安装 OpenSSL-Compatibility-Layer 遇到如下报错
请问大佬们 有遇到吗
烦请指导一下
## 环境：
虚拟机环境搭建CentOS Linux release 7.9.2009 (Core)
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## GmSSL版本：
GmSSL-3.1.1

![1](https://github.com/GmSSL/OpenSSL-Compatibility-Layer/assets/33503157/4c510d5f-f8af-4d0f-a84f-39b5dc906641)

**Comment by github-ace** [comment]
遇到了，犯愁，解决了吗，大佬

**Comment by 1156175523** [comment]
目前我是通过修改源码通过编译的,但是不确定是否对功能有影响(慎重)
我个人感觉是gmssl3.1.1版本变动较大,OpenSSL-Compatibility-Layer没有同步更新导致的
![image](https://github.com/GmSSL/OpenSSL-Compatibility-Layer/assets/33503157/1a9d8654-36af-4096-9692-88afa42d1b5f)

**Comment by github-ace** [comment]
> 目前我是通过修改源码通过编译的,但是不确定是否对功能有影响(慎重) 我个人感觉是gmssl3.1.1版本变动较大,OpenSSL-Compatibility-Layer没有同步更新导致的 ![image](https://private-user-images.githubusercontent.com/33503157/340601795-1a9d8654-36af-4096-9692-88afa42d1b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAwOTgsIm5iZiI6MTcxODY5OTc5OCwicGF0aCI6Ii8zMzUwMzE1Ny8zNDA2MDE3OTUtMWE5ZDg2NTQtMzZhZi00MDk2LTk2OTItODhhZmE0MmQxYjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZmU4YzgzMGNkNjE2OGY5NWY5YzAwOWU5NzBjN2EyNThjYjVlMzlhMGFjMTFjMmI2N2M4MWM2MzAzY2RhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIiKHqwDjd6GfcHO8-kVe9lp8dO-DJsASFngyq3oUZI)

我下载最新的主分支代码，运行没有问题

**Comment by 1156175523** [comment]
> > 目前我是通过修改源码通过编译的,但是不确定是否对功能有影响(慎重) 我个人感觉是gmssl3.1.1版本变动较大,OpenSSL-Compatibility-Layer没有同步更新导致的 ![image](https://private-user-images.githubusercontent.com/33503157/340601795-1a9d8654-36af-4096-9692-88afa42d1b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAwOTgsIm5iZiI6MTcxODY5OTc5OCwicGF0aCI6Ii8zMzUwMzE1Ny8zNDA2MDE3OTUtMWE5ZDg2NTQtMzZhZi00MDk2LTk2OTItODhhZmE0MmQxYjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZmU4YzgzMGNkNjE2OGY5NWY5YzAwOWU5NzBjN2EyNThjYjVlMzlhMGFjMTFjMmI2N2M4MWM2MzAzY2RhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIiKHqwDjd6GfcHO8-kVe9lp8dO-DJsASFngyq3oUZI)
> 
> 我下载最新的主分支代码，运行没有问题

**Comment by 1156175523** [comment]
> > > 目前我是通过修改源码通过编译的,但是不确定是否对功能有影响(慎重) 我个人感觉是gmssl3.1.1版本变动较大,OpenSSL-Compatibility-Layer没有同步更新导致的 ![image](https://private-user-images.githubusercontent.com/33503157/340601795-1a9d8654-36af-4096-9692-88afa42d1b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAwOTgsIm5iZiI6MTcxODY5OTc5OCwicGF0aCI6Ii8zMzUwMzE1Ny8zNDA2MDE3OTUtMWE5ZDg2NTQtMzZhZi00MDk2LTk2OTItODhhZmE0MmQxYjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZmU4YzgzMGNkNjE2OGY5NWY5YzAwOWU5NzBjN2EyNThjYjVlMzlhMGFjMTFjMmI2N2M4MWM2MzAzY2RhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIiKHqwDjd6GfcHO8-kVe9lp8dO-DJsASFngyq3oUZI)
> > 
> > 
> > 我下载最新的主分支代码，运行没有问题

你好 想了解一下你这里下载的最新分支是指OpenSSL-Compatibility-Layer还是gmssl

**Comment by github-ace** [comment]
> > > > 目前我是通过修改源码通过编译的,但是不确定是否对功能有影响(慎重) 我个人感觉是gmssl3.1.1版本变动较大,OpenSSL-Compatibility-Layer没有同步更新导致的 ![image](https://private-user-images.githubusercontent.com/33503157/340601795-1a9d8654-36af-4096-9692-88afa42d1b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAwOTgsIm5iZiI6MTcxODY5OTc5OCwicGF0aCI6Ii8zMzUwMzE1Ny8zNDA2MDE3OTUtMWE5ZDg2NTQtMzZhZi00MDk2LTk2OTItODhhZmE0MmQxYjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZmU4YzgzMGNkNjE2OGY5NWY5YzAwOWU5NzBjN2EyNThjYjVlMzlhMGFjMTFjMmI2N2M4MWM2MzAzY2RhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIiKHqwDjd6GfcHO8-kVe9lp8dO-DJsASFngyq3oUZI)
> > > 
> > > 
> > > 我下载最新的主分支代码，运行没有问题
> 
> 你好 想了解一下你这里下载的最新分支是指OpenSSL-Compatibility-Layer还是gmssl

gmssl

**Comment by 1156175523** [comment]
目前遇到的问题已解决
OpenSSL-Compatibility-Layer-0.8.1
GmSSL需要使用GmSSL-master最新分支代码

**Comment by github-ace** [comment]
> 目前遇到的问题已解决 OpenSSL-Compatibility-Layer-0.8.1 GmSSL需要使用GmSSL-master最新分支代码

但是别人给我的证书用了报错PEM_read_bio_X509_AUX() failed

**Comment by 1156175523** [comment]
> > 目前遇到的问题已解决 OpenSSL-Compatibility-Layer-0.8.1 GmSSL需要使用GmSSL-master最新分支代码
> 
> 但是别人给我的证书用了报错PEM_read_bio_X509_AUX() failed

抱歉,俺也是加密小白
你可以尝试使用自签名证书验证功能(排除证书本身)
参看如下链接：
https://blog.csdn.net/cheng1126su/article/details/137106355

**Comment by 1156175523** [comment]
> > 目前遇到的问题已解决 OpenSSL-Compatibility-Layer-0.8.1 GmSSL需要使用GmSSL-master最新分支代码
> 
> 但是别人给我的证书用了报错PEM_read_bio_X509_AUX() failed

这个问题可以重新提个问题，请求互联网大佬们支持一下
