### ISSUE TITLE
README中"生成服务器TLCP证书"的第四步中的示例命令是不是写错了？

### ISSUE THREAD

**Issue by fengyf** [GmSSL/OpenSSL-Compatibility-Layer#8]
$ gmssl sm2keygen -pass P@ssw0rd -out enckey.pem
执行成功
$ gmssl reqgen -C CN -ST Beijing -L Haidian -O PKU -OU CS -CN localhost -key enckey.pem -pass P@ssw0rd -out encreq
执行成功
$ gmssl reqsign -in encreq.pem -days 365 -key_usage keyEncipherment -cacert cacert.pem -key cakey.pem -pass P@ssw0rd -out enccert.pem
执行失败，报错“找不到encreq.pem文件”，尝试 mv encreq encreq.pem 后再次执行成功，是不是第二个命令中的 -out encreq 应为 -out encreq.pem ，因为刚接触ssl这块，不太敢确定

**Comment by PikaByter** [comment]
是的，我之前尝试的时候也是这样解决的

**Comment by fengyf** [comment]
> 是的，我之前尝试的时候也是这样解决的

thx，转用tongsuo了。
